### ISSUE TITLE
WebAssembly (wasm) target support, faster/smaller than asm.js

### ISSUE THREAD

**Issue by satoshinm** [satoshinm/NetCraft#1]
Build for wasm in addition to asm.js, expected faster but less compatible (requires prerelease browsers at the time of this writing). Build for both and let the user choose, or fallback automatically.

Add `-s WASM=1` to emcc, and BINARYEN_METHOD native-wasm and/or asmjs, refer to: https://github.com/kripken/emscripten/wiki/WebAssembly

**Comment by satoshinm** [comment]
Adding -s WASM to CMakeFiles.txt LINK_FLAGS, it builds but cannot test locally due to promise fetch API:

craft.js:1806 Fetch API cannot load file:////NetCraft/build/craft.wasm. URL scheme must be "http" or "https" for CORS request.
Uncaught (in promise) TypeError: Failed to fetch
    at getBinaryPromise (craft.js:1806)
    at doNativeWasm (craft.js:1877)
    at Object.Module.asm (craft.js:2027)
    at craft.js:9827

run from a local server:

python -m SimpleHTTPServer

then http://localhost:8000/craft.html - this works in Chrome 57.0.2987.133, and seems snappier. The wasm build output with emscripten is a lot smaller:

```
build $ ls -lh craft*
-rw-r--r--  1 admin  staff   100K Apr  4 22:24 craft.html
-rw-r--r--  1 admin  staff   1.1M Apr  4 22:24 craft.js
-rw-r--r--  1 admin  staff   2.6M Apr  4 22:24 craft.wasm
```

than the asm.js emscripten output:

```
build $ ls -lh craft*
-rw-r--r--  1 admin  staff   100K Apr  4 22:32 craft.html
-rw-r--r--  1 admin  staff    14M Apr  4 22:32 craft.js
```

1.1M + 2.6M = 3.7M for wasm vs 14M for asm.js. But the downside is less browser compatibility, just hangs in Safari Technical Preview. So the asm.js-based emscripten build would still be needed. 

Question now is how to integrate this variant into the build system. Make it a cmake option (to add to the arguments of `cmake -DCMAKE_TOOLCHAIN_FILE=$EMSCRIPTEN/cmake/Modules/Platform/Emscripten.cmake ..`)? Or maybe better, always build both asm.js and wasm (run build twice?), then load either with a fallback?

**Comment by satoshinm** [comment]
Added for GH-45 and this a wasm build type:

```sh
mkdir wasm-build
cmake -DWASM=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$EMSCRIPTEN/cmake/Modules/Platform/Emscripten.cmake ..
make
```

However, wasm used to work, when I first tried it -- but now, get an out-of-memory access?!

craft.html:1251 exception thrown: RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at  (<WASM>[273]+70)
    at  (<WASM>[279]+40)
    at Object.Module._main (http://localhost:8000/craft.js:1:827350)
    at Object.callMain (http://localhost:8000/craft.js:1:836819)
    at doRun (http://localhost:8000/craft.js:1:837562)
    at http://localhost:8000/craft.js:1:837712

![screen shot 2017-04-10 at 11 24 25 pm](https://cloud.githubusercontent.com/assets/26856618/24895370/d8e31164-1e44-11e7-9caa-24b53e806b98.png)

What changed? Need to regress to 4/4, isolate

**Comment by satoshinm** [comment]
![screen shot 2017-04-11 at 12 01 15 am](https://cloud.githubusercontent.com/assets/26856618/24896493/0b4f6260-1e4a-11e7-8473-8203b60f52c6.png)
